_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
alpha:
    value: 0.41422164871505096
temperature:
    value: 1.1540633524462296
